### ISSUE TITLE
App crashes on opening the profile page multiple times

### ISSUE THREAD

**Issue by ApoorvaAditya** [HackIllinois/android#430]
## Steps to Reproduce:
 - Checkout branch `staff_scanner`
 - Open the profile page
 - Wait 5 seconds
 - Go to another page
 - Go back to the profile page
 - Try this multiple times if it doesn't occur the first time

## Probable Cause
The qr code is not being generated correctly. The width is 0 for some reason.

## Error Log:
```
FATAL EXCEPTION: main
Process: org.hackillinois.android, PID: 6321
java.lang.IllegalArgumentException: width must be > 0
    at android.graphics.Bitmap.checkWidthHeight(Bitmap.java:450)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:1188)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:1228)
    at org.hackillinois.android.view.profile.ProfileFragment.generateQR(ProfileFragment.kt:200)
    at org.hackillinois.android.view.profile.ProfileFragment.updateQrView(ProfileFragment.kt:172)
    at org.hackillinois.android.view.profile.ProfileFragment.onCreate$lambda-1(ProfileFragment.kt:58)
    at org.hackillinois.android.view.profile.ProfileFragment.$r8$lambda$dg3Bd_UJBMUEJB6T1vcFDWeSBNk(Unknown Source:0)
    at org.hackillinois.android.view.profile.ProfileFragment$$ExternalSyntheticLambda4.onChanged(Unknown Source:4)
    at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
    at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
    at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
    at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7656)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by leahlud** [comment]
Did you experience this crashing before having access to the [Profile Fixed Bug PR](https://github.com/HackIllinois/android/pull/421)? I believe I fixed the problem with the Bitmap width in that.

**Comment by ApoorvaAditya** [comment]
Ah I think the `staff_scanner` branch doesn't have the fixes. Once we merge then it will probably be fixed 👍
